#=================================================================
# minio (上传图片需要，需配置成自己的地址)
#=================================================================
minio:
  endpoint: http://127.0.0.1:9000
  accessKey: ernest
  secretKey: lzk100207

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/your_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: hDJph7CNmIa+N6BUMutTc9/bbKxdilgiMAjmdHfj9fTwGeY5Ed/Nlb8sy8vHI6AeAhSbHvDi+Dq+VK6nNg3x9A==
    driver-class-name: com.mysql.cj.jdbc.Driver

