server:
  port: 8000 # 指定启动端口
spring:
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://insta-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: user
          uri: lb://insta-user
          predicates:
               - Path=/user/**

sa-token:
  token-name: Authorization
  # token前缀
  token-prefix: Bearer
  token-style: random-128