server:
  port: 8000 # 指定启动端口
spring:
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://insta-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: user
          uri: lb://insta-user
          predicates:
               - Path=/user/**
        - id: note
          uri: lb://insta-note
          predicates:
              - Path=/note/**
          filters:
              - StripPrefix=1
        - id: user-relation
          uri: lb://insta-user-relation
          predicates:
              - Path=/relation/**
          filters:
              - StripPrefix=1

sa-token:
  token-name: Authorization
  # token前缀
  token-prefix: Bearer
  token-style: random-128
